/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Message, } from "./utils/message";
export namespace Components {
    interface AppChat {
        "chatMessageList": Message[];
        "sendChatMessage": (message: string) => void;
        "updateReadChatMessageCount": (count: number) => void;
    }
    interface AppGame {
    }
    interface AppGameCodenames {
    }
    interface AppGameWhoIsTheSpy {
    }
    interface AppHome {
        "appendMessage": (message: {
            nickname: string;
            message: string;
        }) => void;
        "connectToPeer": (peerId: string) => void;
        "createPeer": (peerId?: string) => void;
        "hostId": string;
        "nickname": string;
        "peerId": string;
        "updateNickname": (nickname: string) => void;
    }
    interface AppRoot {
    }
    interface AppTabs {
        "unreadMessageCount": number;
    }
}
declare global {
    interface HTMLAppChatElement extends Components.AppChat, HTMLStencilElement {
    }
    var HTMLAppChatElement: {
        prototype: HTMLAppChatElement;
        new (): HTMLAppChatElement;
    };
    interface HTMLAppGameElement extends Components.AppGame, HTMLStencilElement {
    }
    var HTMLAppGameElement: {
        prototype: HTMLAppGameElement;
        new (): HTMLAppGameElement;
    };
    interface HTMLAppGameCodenamesElement extends Components.AppGameCodenames, HTMLStencilElement {
    }
    var HTMLAppGameCodenamesElement: {
        prototype: HTMLAppGameCodenamesElement;
        new (): HTMLAppGameCodenamesElement;
    };
    interface HTMLAppGameWhoIsTheSpyElement extends Components.AppGameWhoIsTheSpy, HTMLStencilElement {
    }
    var HTMLAppGameWhoIsTheSpyElement: {
        prototype: HTMLAppGameWhoIsTheSpyElement;
        new (): HTMLAppGameWhoIsTheSpyElement;
    };
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLAppTabsElement extends Components.AppTabs, HTMLStencilElement {
    }
    var HTMLAppTabsElement: {
        prototype: HTMLAppTabsElement;
        new (): HTMLAppTabsElement;
    };
    interface HTMLElementTagNameMap {
        "app-chat": HTMLAppChatElement;
        "app-game": HTMLAppGameElement;
        "app-game-codenames": HTMLAppGameCodenamesElement;
        "app-game-who-is-the-spy": HTMLAppGameWhoIsTheSpyElement;
        "app-home": HTMLAppHomeElement;
        "app-root": HTMLAppRootElement;
        "app-tabs": HTMLAppTabsElement;
    }
}
declare namespace LocalJSX {
    interface AppChat {
        "chatMessageList"?: Message[];
        "sendChatMessage"?: (message: string) => void;
        "updateReadChatMessageCount"?: (count: number) => void;
    }
    interface AppGame {
    }
    interface AppGameCodenames {
    }
    interface AppGameWhoIsTheSpy {
    }
    interface AppHome {
        "appendMessage"?: (message: {
            nickname: string;
            message: string;
        }) => void;
        "connectToPeer"?: (peerId: string) => void;
        "createPeer"?: (peerId?: string) => void;
        "hostId"?: string;
        "nickname"?: string;
        "peerId"?: string;
        "updateNickname"?: (nickname: string) => void;
    }
    interface AppRoot {
    }
    interface AppTabs {
        "unreadMessageCount"?: number;
    }
    interface IntrinsicElements {
        "app-chat": AppChat;
        "app-game": AppGame;
        "app-game-codenames": AppGameCodenames;
        "app-game-who-is-the-spy": AppGameWhoIsTheSpy;
        "app-home": AppHome;
        "app-root": AppRoot;
        "app-tabs": AppTabs;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-chat": LocalJSX.AppChat & JSXBase.HTMLAttributes<HTMLAppChatElement>;
            "app-game": LocalJSX.AppGame & JSXBase.HTMLAttributes<HTMLAppGameElement>;
            "app-game-codenames": LocalJSX.AppGameCodenames & JSXBase.HTMLAttributes<HTMLAppGameCodenamesElement>;
            "app-game-who-is-the-spy": LocalJSX.AppGameWhoIsTheSpy & JSXBase.HTMLAttributes<HTMLAppGameWhoIsTheSpyElement>;
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "app-tabs": LocalJSX.AppTabs & JSXBase.HTMLAttributes<HTMLAppTabsElement>;
        }
    }
}
